services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    platform: linux/amd64
    ports:
      - "8080:8080"
    volumes:
      - shared-data:/app/data  
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "8050:8050"
    environment:
      - BACKEND_URL=http://backend:8080
    volumes:
      - shared-data:/app/data 
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  shared-data:
    driver: local
